#! /bin/bash

set -e
( cd build && ./run-build )

mkdir -p production/dist
cp -r build/dist/* production/dist/
( cd production && ./build-production-image )

echo Created bevly/bevly docker image, you may now 'docker push bevly/bevly'
