#! /bin/bash

set -e

echo "Creating MongoDB docker container (bevly-mongodb)"
docker run --name bevly-mongodb -d dockerfile/mongodb

sleep 2
echo "Creating Bevly docker container (bevly-docker)"
bevly-create-app-container
